# Generated by Django 4.0.3 on 2022-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_documents_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(max_length=250, upload_to='uploads/'),
        ),
    ]
